### ISSUE TITLE
display error

### ISSUE THREAD

**Issue by sistemmsn** [jjcamarasa/nagvis-icons#1]
I get this error, I don't understand why

<img width="488" alt="image" src="https://github.com/jjcamarasa/nagvis-icons/assets/38023703/ad4950ac-a24b-4fdf-a706-f4319b142e3c">

define global {
alias=Mapa de calor
parent_map=cpd
object_id=0
iconset=cube-host  ->error
label_show=1
label_y=+17
label_background=transparent
label_border=transparent
label_style=color:#fff;font-size:2em;
label_maxlen=13
background_color=#0B0C0E
}

define textbox {
text=ESTADO GENERAL DE LOS SISTEMAS
x=10
y=0
w=1080
h=24
object_id=40b48a
border_color=transparent
background_color=transparent
style=color:#FFFFFF;font-size:3.5em;
}

**Comment by jjcamarasa** [comment]
Hi, you must have an iconset named "cube-host" in your nagvis icons folder.
If you remove line or comment it nagvis will use default iconset.
